server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/username/Dev/projects/spring-cloud/git-local-repo
          # file ???? ??
          # ex) http://localhost:8888/{?? ???}/{profile}
            # ? uri(directory)? ??? ?? ??? ??? {?? ???} ??? ?? ???? ?? ??? ?? ? ??.
            # ex) ?? ??? ecommerce.yml? ??, `.../ecommerce/default`? ?? ??