server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/username/Dev/study/projects/spring-cloud/git-local-repo  # local에서 실행 시 directory 맞는지 확인
          # 설정 파일의 위치 (local)
          # local에서 `/{설정파일명}/{profile}`로 호출하여 관련 정보 확인 가능
            # ex) http://localhost:8888/{설정파일명}/{profile}
            # ex) http://localhost:8888/ecommerce/test